### ISSUE TITLE
AccessTokenResponse contains non-standard attribute

### ISSUE THREAD

**Issue by vakhtang** [ocadotechnology/sttp-oauth2#112]
I'm running into a decoding failure when attempting a client credentials grant because my identity service is not returning a value for `domain` that `AccessTokenResponse` expects: https://github.com/ocadotechnology/sttp-oauth2/blob/b605d0be2f943e66a4c38931a3ba71c9e39c966c/oauth2/src/main/scala/com/ocadotechnology/sttp/oauth2/ClientCredentialsToken.scala#L24-L29

According to the [OAuth 2.0 spec](https://datatracker.ietf.org/doc/html/rfc6749#section-5.1) the only valid attributes for the response are `access_token`, `token_type`, `expires_in`, `refresh_token`, and `scope`.

Can `domain` be made optional, or have I missed something here? I'm using `0.10.1` of your library.

**Comment by kubukoz** [comment]
Thanks for reporting!

Had a quick look, this seems to check out but I'll defer to the local expert @majk-p 😅

**Comment by vakhtang** [comment]
Thanks for the prompt response @kubukoz. I'm happy to open a PR for the change if we all agree it's the correct approach.

**Comment by majk-p** [comment]
Hi @vakhtang, thanks for the report! You are right that we don't follow the OAuth spec here, and we should fix that.
We were thinking about solution similar to this one: https://github.com/ocadotechnology/sttp-oauth2/pull/104 introduced for AuthorizationCodeGrant. The bottom line would be to allow end user to specify the response type, while we'd provide a basic one (similar to `OAuth2TokenResponse.Basic`).
If you are willing to implement it that way, we are happy to accept a contribution :+1:

**Comment by kubukoz** [comment]
@majk-p the default one should still be spec compliant, so we should probably make the field optional (and eventually remove it) anyway 😅

**Comment by majk-p** [comment]
On one hand it makes sense to go step by step, making the field optional. On the other hand both of those are breaking the API and we'd like to have as few of them as possible.

**Comment by majk-p** [comment]
I've looked into it, and it seems using generic solution described above might be an overkill. We might revisit this idea later, but I've prepared a PR fixing this specific issue in https://github.com/ocadotechnology/sttp-oauth2/pull/114

**Comment by majk-p** [comment]
@vakhtang fix is now merged and released with `v.0.11.0`
