### ISSUE TITLE
Add support for omitting scope

### ISSUE THREAD

**Issue by vakhtang** [ocadotechnology/sttp-oauth2#124]
Hey all, it'd be nice if there existed an ability to omit the scope, since scope is optional. Based on the [spec](https://datatracker.ietf.org/doc/html/rfc6749#section-3.3) it looks like the scope cannot be empty if a value *is* being passed, so introducing `Scope.empty` or a similar value is probably not the right thing to do here, although that'd be the most expedient solution.

**Comment by blondacz** [comment]
This is to omit scope from a request but same neds to be done on response, as the scope on response is required only when different from scope in request

**Comment by majk-p** [comment]
Implemented in https://github.com/ocadotechnology/sttp-oauth2/pull/199, released as `v0.14.0-RC1`
