### ISSUE TITLE
Caching instance of TokenIntrospection

### ISSUE THREAD

**Issue by matwojcik** [ocadotechnology/sttp-oauth2#296]
Create caching instance of `TokenIntrospection` in similar manner to `CachingAccessTokenProvider`.

https://www.oauth.com/oauth2-servers/token-introspection-endpoint/

> Consumers of the introspection endpoint may wish to cache the response of the endpoint for performance reasons. As such, it is important to consider the performance and security trade-offs when deciding to cache the values. For example, shorter cache expiration times will result in higher security since the resource servers will have to query the introspection endpoint more frequently, but will result in an increased load on the endpoint. Longer expiration times leave a window open where a token may actually be expired or revoked, but still be able to be used at a resource server for the remaining duration of the cache time.
> 
> One way to mitigate this problem is for consumers to never cache the value beyond the expiration time of the token, which would have been returned in the “exp” parameter of the introspection response.

Things to consider:
- don't cache longer than `exp`
- consider memory consumption
- consider concurrent access to cache and retrieval of tokens
- make it cache provider agnostic, provide separate modules with concrete implementations (but it is reasonable to start with one)

**Comment by kubukoz** [comment]
Closed in #298 (I think) :)

**Comment by matwojcik** [comment]
And #299 ;)
