### ISSUE TITLE
Client credentials backend (interceptor) module

### ISSUE THREAD

**Issue by bwiercinski** [ocadotechnology/sttp-oauth2#40]
I would like to add a new module with backend implementation, that is:

 * taking another SttpBackend as an input
 * gets a new token with given scope
 * adds header "Bearer"
 * saves the token in some `Ref`
 * checks if the token is not expired and reuses it

After consultations with @majk-p I believe that such backend only makes sense in the case of the ClientCredentials functionality (i.e. app2app communication https://tools.ietf.org/html/rfc6749#section-4.4)

That's why I suggest following names:

1. `sttp-oauth2-app-to-app-backend`, class name: SttpOauth2AppToAppBackend
1. `sttp-oauth2-client-credentials-backend`, class name: SttpOauth2ClientCredentialsBackend
1. `sttp-oauth2-backend`, class name: SttpOauth2Backend
1. `sttp-oauth2-app-to-app`, class name: SttpOauth2AppToApp
1. other?

(alternatively instead of `sttp-oauth2-app-to-app` prefix we can use `sttp-oauth2-app2app`, but it looks strange with doubled "2")

**other topic:**

I need some engine to store currently valid token. one option is to use cats effect's `Ref`, but many of our clients may not want to have CE in their classpaths (just like sttp::core). Since this logic is very simple we can use `AtomicReference` for that. WDYT?

**Comment by majk-p** [comment]
For a module name, `sttp-oauth2-backend` sounds good. In case we want to provide any other authenticated backends in future, this sounds like a resonable place. Regarding class I'd probably go with `SttpOauth2ClientCredentialsBackend` as this leaves us with space to define other backends without name conflicts.
@tplaskowski @kubukoz wdyt?

**Comment by majk-p** [comment]
About the `Ref` vs `AtomicReference`, I'd say we can have this discussion in the PR, but minimizing the library dependencies seems like a reasonable argument to avoid going with `CE` if there's a sane alternative.

**Comment by tplaskowski** [comment]
If there is a separate module in place then it could have a dependency on `CE`, because as a user if I use `CE` and I rely on that effect model then I would like to have it out-of-the-box in the library. So, that could be `sttp-oauth2-cats-backends`. In the future, there could be a module for `zio`, etc.

**Comment by kubukoz** [comment]
If you want to keep a functional codebase AtomicReference without Sync is a no-no. CE core isn't a very heavy dependency to have (even more so after the switch to CE3 kernel happens), so I'd go that way, potentially with some reusable core part that could be shared by both CE/zio/etc modules.

Also keep in mind that caching with just Ref is difficult to get right if you want to avoid duplicate fetches, so something like cats-effect's MVar2 would be advised (note that it's going to disappear without a replacement in CE3, and a limited version of MVar is available in monix-catnap, buy this will be significantly easier to implement right in CE3 without MVar).

**Comment by bwiercinski** [comment]
I was thinking about that, and I think We were approaching it from the wrong end.

Sttp have it's own abstraction over effects: https://github.com/softwaremill/sttp-shared/blob/master/core/src/main/scala/sttp/monad/MonadError.scala

As the name of this project suggests, this library is an extension for the sttp, not for the cats. We should stick as much as possible to practices and concepts from the `sttp`. I briefly look at the present usage of cats in this library, and I believe it can be easily replaced with sttp MonadError.

**Comment by kubukoz** [comment]
Sure, it's an extension for sttp, but we treated cats as a sort of standard library ;)

As for the existing usage, that can probably be replaced with sttp's MonadError indeed... apparently their instance also has `suspend` `(I have no idea how it's supposed to work for the Future instance though 😂 ), so in theory we could reimplement `Ref` (or something similar) using `suspend` + `AtomicReference`. Still, that's not enough to avoid duplicate fetches.

To be clear, the situation I'm talking about is:

1. method A calls the backend, there's no cached token or it's outdated. A token fetch starts
2. method B calls the backend, there's no cached token or it's outdated. A token fetch starts
3. now you have two concurrent fetches
4. method B/A's fetch got a token, saves it
5. method A/B's fetch got a token, overwrites the one we just saved

Assuming generating a token doesn't disable the previous one, this is probably fine, if the overhead of making redundant duplicate requests is acceptable. Up to you ;)

**Comment by kubukoz** [comment]
Mentioned offline in a discussion with @bwiercinski, another way to avoid duplicate fetches is to keep a background process responsible for updating the token periodically. This way you also ensure a request never has to wait for a fetch, because there's always a token in the storage - at the cost of refreshing even if there's no traffic that needs the token.

**Comment by bwiercinski** [comment]
well I never saw such strategy. I would stick to lazy strategy (described in original post) as default

**Comment by tplaskowski** [comment]
Still, as a client I would like to do a cache lookup in my target effect type.

In my opinion, if you don't wan't to go with a specific module with library dependency, then you should abstract the caching and provide backend where you will pass the loopup function.  
Think that the user would have, say `secondAppId => F[Token]` - you would like that to be in your effect - maybe you wan't to store it in a `Ref`, maybe in Redis, maybe in an microservice etc.

**Comment by kubukoz** [comment]
> Still, as a client I would like to do a cache lookup in my target effect type.

Why would you need to lookup the cache on your own? That's what the module is supposed to do for you :P 

and anyway, it can be exposed in your effect type if it has an sttp MonadError (as @bwiercinski pointed out).

Mild +1 for abstracting out the lookup / save methods (wink wink https://github.com/cb372/scalacache), now that I think about it, this transition can be made transactional / deduplicated more easily using `Semaphore`, if we were to actually use Cats Effect.

**Comment by tplaskowski** [comment]
> Why would you need to lookup the cache on your own? That's what the module is supposed to do for you :P

Because I would like to have control over it.

Of course, we could have some basic implementation, and probably you can go even without checking eviction time but refresh the token on the first error, but I would rather abstract it away and give that power to the users.

Besides, we all know that there are _two hard things_ in computer science, and we have all of them in this discussion :P

**Comment by kubukoz** [comment]
Maybe if you need that much control you don't want to inject your get/set functions and have the library call that (inversion of control), but get a reusable set of functions that you can compose however you like - which is already there 😅 

anyway, I think it's a reasonable idea to have one "constructor" that takes a set of functions for getting/setting the cached value (e.g. `Cache[F, Token]`) and a default one that uses an internal Ref. Or the other way around, make this return a new subtype of `SttpBackend` with a `get: F[Option[Token]]` method added for read access only (so the backend would be fully in control of the writes).

**Comment by bwiercinski** [comment]
> Besides, we all know that there are two hard things in computer science, and we have all of them in this discussion :P

good point :smile: 

First of all, if a user want to have control over the process, he should implement it by himself. The interceptor should encapsulate details. I wish not adding an api returning current token.

Keep in mind, that the cache, which will contain type `Option[Token]`, have to be created per instance of the `SttpOauth2ClientCredentialsBackend` (draft name). A user can create 1 backend with scope X and another with scope Y.

Trivial implementation using cats' `Ref` and `Semaphore` will create a `Ref[Option[Token]]` per instance, so we have mentioned problem solved for free.

If we would like to use Redis, then each instance of the`SttpOauth2ClientCredentialsBackend` would have to have some identifier to know where the token is placed in Redis. Then implementing  proposed `Cache[F, Token]` is not so easy considering many instances of the backend

**Comment by kubukoz** [comment]
👍 for encapsulation!

as for `Cache[F, Token]`, if you pass it explicitly it becomes much easier.

I'd say let's solve the immediate need (if there is one) and implement the encapsulated interface (so, just SttpBackend with a custom "constructor" function) - we can always break and enrich it later.
