### ISSUE TITLE
Circe cleanup

### ISSUE THREAD

**Issue by majk-p** [ocadotechnology/sttp-oauth2#5]
In `circe` object there's a configuration and codec for seconds available. Those should be used in whole library, especially in `Oauth2TokenResponse.scala` and `RefreshTokenResponse.scala`.

**Comment by kubukoz** [comment]
If we remove auto-generated codecs and the `circe-generic*` dependencies, this won't be necessary anymore as there won't be a Configuration class :)

**Comment by kubukoz** [comment]
Cloesd in #18
