### ISSUE TITLE
jsoniter-scala

### ISSUE THREAD

**Issue by goral09** [ocadotechnology/sttp-oauth2#8]
Have you considered using https://github.com/plokhotnyuk/jsoniter-scala for JSON (de)serialization?

**Comment by kubukoz** [comment]
I think it's beyond the scope for now, but who's to say whether we'll allow more flexibility in the future :) 

If enough people think this is worthwhile, I think there's a fair chance it'll happen.

**Comment by majk-p** [comment]
Implemented in https://github.com/ocadotechnology/sttp-oauth2/pull/351
