### ISSUE TITLE
Support custom login/token URLs

### ISSUE THREAD

**Issue by kubukoz** [ocadotechnology/sttp-oauth2#9]
e.g. Spotify uses an `/authorize` path instead of `/login`.

Current workaround: 

`val uri = AuthorizationCodeProvider[Uri, F].loginLink(scope = scopes).path("authorize")`

A similar situation happens for the `/token` path - in Spotify it's `/api/token`.

**Comment by bwiercinski** [comment]
we can also consider adding in `com.ocadotechnology.sttp.oauth2.AuthorizationCodeProvider#uriInstance` a parameter, something like: `case class AuthorizationCodeConfig(loginPath=List("login"), logoutPath=List("logout"))`

**Comment by kubukoz** [comment]
Yeah, that would probably work best
